export const TITLE_AUTHOR = 'Justin A. Harrison'
export const TITLE_DESCRIPTION = 'A Visual Dialogue of Wisdom from Wondering'
export const TITLE_EMAIL = 'justinadenharrison@gmail.com'
export const TITLE_HEADER = 'Sographes'
export const TITLE_VERSION = '0.0.0'
